---

title: Movies and Series Data Warehouse Dimensional Model

---

erDiagram
    Dim_Date {
        int id
        string complete_date
        int year
        int month
        int quarter
        int week
        int day
    }

    Dim_Movie {
        int id
        int tmdb_id
        string imdb_id

        string title
        string original_title
        array(string) genre
    }

    Fact_MediaEvaluation {
        int id
        int movie_id
        int series_id
        int artist_id

        int ingestion_date
        int release_date
        int end_date

        int minute_duration
        float vote_average
        int vote_count
    }

    Dim_Series {
        int id
        int tmdb_id
        string imdb_id
    }

    Dim_Artist {
        int id
        string name
        string genre
        int birth_year
        int death_year
        array(string) occupation
    }


    Fact_MediaEvaluation }o--|| Dim_Movie : movie_id
    Fact_MediaEvaluation }o--|| Dim_Series : series_id
    Fact_MediaEvaluation }o--|| Dim_Artist : artist_id

    Dim_Date ||--o{ Fact_MediaEvaluation : ingestion_date
    Dim_Date ||--o{ Fact_MediaEvaluation : release_date
    Dim_Date ||--o{ Fact_MediaEvaluation : end_date
